import type { RegistryEntry } from '../types.js';

/** Registry entries for the performance category (10 live checkers). */
export const performanceCheckers: ReadonlyArray<RegistryEntry> = [
  {
    id: 'compression-enabled',
    name: 'Gzip/Brotli on text responses',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'Sends request with `Accept-Encoding: gzip, br`; checks `Content-Encoding` in response.',
    consumes: ['rootResponse'],
  },
  {
    id: 'core-web-vital-cls',
    name: 'CLS < threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'Cumulative Layout Shift is below the `cls` threshold (default 0.1).',
    consumes: ['lighthouse'],
    thresholdKeys: ['cls'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'core-web-vital-inp',
    name: 'INP < threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'Interaction to Next Paint is below the `inp` threshold (default 200ms).',
    consumes: ['lighthouse'],
    thresholdKeys: ['inp'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'core-web-vital-lcp',
    name: 'LCP < threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'Largest Contentful Paint is below the `lcp` threshold (default 2500ms).',
    consumes: ['lighthouse'],
    thresholdKeys: ['lcp'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'font-preload-and-display-swap',
    name: 'Fonts preloaded + font-display: swap',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description:
      'Checks `<link rel="preload" as="font">` for primary fonts; fetches CSS, scans for `font-display: swap`.',
    consumes: ['dom', 'http'],
  },
  {
    id: 'lighthouse-accessibility-score',
    name: 'Lighthouse Accessibility ≥ threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'Lighthouse Accessibility category score is at or above the `lighthouse-accessibility` threshold (default 90).',
    consumes: ['lighthouse'],
    thresholdKeys: ['lighthouse-accessibility'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'lighthouse-best-practices-score',
    name: 'Lighthouse Best Practices ≥ threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'Lighthouse Best Practices category score is at or above the `lighthouse-best-practices` threshold (default 90).',
    consumes: ['lighthouse'],
    thresholdKeys: ['lighthouse-best-practices'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'lighthouse-performance-score',
    name: 'Lighthouse Performance ≥ threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'Lighthouse Performance category score is at or above the `lighthouse-performance` threshold (default 90).',
    consumes: ['lighthouse'],
    thresholdKeys: ['lighthouse-performance'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'lighthouse-seo-score',
    name: 'Lighthouse SEO ≥ threshold',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'Lighthouse SEO category score is at or above the `lighthouse-seo` threshold (default 90).',
    consumes: ['lighthouse'],
    thresholdKeys: ['lighthouse-seo'],
    requiresPeerDep: 'puppeteer',
  },
  {
    id: 'static-asset-cache-headers',
    name: 'Cache-Control on static assets',
    category: 'performance',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description:
      'Extracts `<script>`, `<link rel="stylesheet">`, `<img>` URLs from DOM; HEAD each; checks `Cache-Control` is long-lived (max-age ≥ 86400). Emits one consolidated result per asset class.',
    consumes: ['dom', 'http'],
    emitsMultipleResults: true,
  },
] as const;
