import type { RegistryEntry } from '../types.js';

/** Registry entries for the security category (15 checkers: 1 static + 14 live). */
export const securityCheckers: ReadonlyArray<RegistryEntry> = [
  {
    id: 'clickjacking-protection',
    name: 'X-Frame-Options or CSP frame-ancestors',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'Either `X-Frame-Options: DENY/SAMEORIGIN` OR CSP with `frame-ancestors` directive.',
    consumes: ['rootResponse'],
  },
  {
    id: 'cors-not-wildcard',
    name: 'CORS not wildcard in production',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'critical',
    description:
      'OPTIONS request via configured `probePath` (default `/`); checks `Access-Control-Allow-Origin` is not `*`. Also consumes ad-hoc `http`.',
    consumes: ['rootResponse', 'http'],
    optionsKey: 'cors-policy',
  },
  {
    id: 'csp-present',
    name: 'Content-Security-Policy header present',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'Header check; warns if uses `unsafe-inline` or `unsafe-eval` without nonce/hash.',
    consumes: ['rootResponse'],
  },
  {
    id: 'dkim-record',
    name: 'DKIM record present for each configured selector',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'DKIM TXT record is present at `<selector>._domainkey.<domain>` for each configured selector. Self-skips when `email-auth.enabled` is false.',
    consumes: ['dns'],
    optionsKey: 'email-auth',
  },
  {
    id: 'dmarc-record',
    name: 'DMARC record present',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description:
      'DMARC TXT record is present at `_dmarc.<domain>`. Self-skips when `email-auth.enabled` is false.',
    consumes: ['dns'],
    optionsKey: 'email-auth',
  },
  {
    id: 'hsts-present',
    name: 'Strict-Transport-Security header present',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'critical',
    description: 'Header check + parses `max-age`; warns if max-age < 15768000 (6 months).',
    consumes: ['rootResponse'],
  },
  {
    id: 'https-enforcement',
    name: 'HTTP redirects to HTTPS',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'critical',
    description:
      'GET against `http://` variant of URL; expects redirect chain ending at `https://`. Also consumes ad-hoc `http`.',
    consumes: ['rootResponse', 'http'],
  },
  {
    id: 'permissions-policy-present',
    name: 'Permissions-Policy header present',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description: 'Header presence; no value validation in v1.',
    consumes: ['rootResponse'],
  },
  {
    id: 'referrer-policy-present',
    name: 'Referrer-Policy header present',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description: 'Any valid Referrer-Policy value.',
    consumes: ['rootResponse'],
  },
  {
    id: 'secret-scan',
    name: 'No hardcoded secrets',
    category: 'security',
    mode: 'static',
    defaultEnabled: true,
    maxSeverity: 'critical',
    description:
      'Scans source files for known secret patterns (API keys, tokens, private keys, credentials). User-configurable via the `secret-scan` options.',
    optionsKey: 'secret-scan',
    emitsMultipleResults: true,
  },
  {
    id: 'server-headers-suppressed',
    name: 'Server / X-Powered-By suppressed',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: '`Server` and `X-Powered-By` headers absent or generic (no version info).',
    consumes: ['rootResponse'],
  },
  {
    id: 'spf-record',
    name: 'SPF record present',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'SPF TXT record is present at the configured domain. Self-skips when `email-auth.enabled` is false.',
    consumes: ['dns'],
    optionsKey: 'email-auth',
  },
  {
    id: 'ssl-not-expiring',
    name: 'SSL certificate not expiring within N days',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description:
      'TLS certificate does not expire within the configured warning window (`ssl-expiry-warning-days`).',
    consumes: ['tls'],
    thresholdKeys: ['ssl-expiry-warning-days'],
  },
  {
    id: 'ssl-valid',
    name: 'SSL certificate valid',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'critical',
    description: 'TLS certificate is valid and trusted by the system root store.',
    consumes: ['tls'],
  },
  {
    id: 'x-content-type-options-nosniff',
    name: 'X-Content-Type-Options: nosniff',
    category: 'security',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'Header equals `nosniff`.',
    consumes: ['rootResponse'],
  },
] as const;
