import type { RegistryEntry } from '../types.js';

/** Registry entries for the seo category (11 live checkers). */
export const seoCheckers: ReadonlyArray<RegistryEntry> = [
  {
    id: 'canonical-url',
    name: 'Canonical URL set',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: '`<link rel="canonical" href="...">` exists.',
    consumes: ['dom'],
  },
  {
    id: 'favicon-present',
    name: 'Favicon present',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description: '`<link rel="icon">` in DOM OR `/favicon.ico` returns 200.',
    consumes: ['dom', 'http'],
  },
  {
    id: 'heading-hierarchy',
    name: 'No skipped heading levels',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description: 'Walks heading tree, flags level jumps (e.g., h2 → h4).',
    consumes: ['dom'],
  },
  {
    id: 'meta-description-present',
    name: 'Meta description present',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: '`<meta name="description">` exists, non-empty, length 50–160 (warn outside).',
    consumes: ['dom'],
  },
  {
    id: 'open-graph-tags',
    name: 'og:title, og:description, og:image present',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description:
      'All three `<meta property="og:*">` tags present. Multi-result: one per missing tag.',
    consumes: ['dom'],
    emitsMultipleResults: true,
  },
  {
    id: 'robots-txt-accessible',
    name: 'robots.txt fetchable and not blocking production',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'GET `/robots.txt`; expects 200; warns if `Disallow: /` is set.',
    consumes: ['dom', 'http'],
  },
  {
    id: 'single-h1',
    name: 'Exactly one H1 per page',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'Count of `<h1>` elements === 1.',
    consumes: ['dom'],
  },
  {
    id: 'sitemap-xml-accessible',
    name: 'sitemap.xml fetchable',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: 'GET `/sitemap.xml`; expects 200 + valid XML.',
    consumes: ['dom', 'http'],
  },
  {
    id: 'structured-data',
    name: 'JSON-LD structured data present',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description: 'At least one `<script type="application/ld+json">` block with parseable JSON.',
    consumes: ['dom'],
  },
  {
    id: 'title-tag-present',
    name: 'Unique title tag present',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'major',
    description: '`<title>` exists, non-empty, length 10–60 chars (warn outside range).',
    consumes: ['dom'],
  },
  {
    id: 'twitter-card-tags',
    name: 'Twitter Card tags present',
    category: 'seo',
    mode: 'live',
    defaultEnabled: true,
    maxSeverity: 'minor',
    description:
      '`<meta name="twitter:card">` and at least one of `twitter:title`/`twitter:description`. Multi-result: one per missing tag.',
    consumes: ['dom'],
    emitsMultipleResults: true,
  },
] as const;
